# Site settings
title: Zzi`s Laboratory
description: 'Development & Study'
url: https://jsy1110.github.io
baseurl: ''
google_analytics: 'UA-223932880-1'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: '지승영'
  email: jsy11101@gmail.com
  github_username:  jsy1110
  linkedin_username:  seungyoung-ji000

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate', 'jekyll-sitemap']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
